### ISSUE TITLE
Text not floating on the correct view

### ISSUE THREAD

**Issue by norrisboat** [UFreedom/FloatingText#2]
For some reason it worked well the first time i tried it but since then the text doesn't float on the correct view anymore. Here's my code:

```
private FloatingText  cubicFloatingText;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_anagram);

    initView(); // initiate all my views with findviewbyid

    cubicFloatingText = new FloatingText.FloatingTextBuilder(Anagram.this)
            .textColor(Color.RED)
            .textSize(100)
            .floatingAnimatorEffect(new CurvePathFloatingAnimator())
            .floatingPathEffect(new CurveFloatingPathEffect())
            .textContent("HELLO")
            .build();
    cubicFloatingText.attach2Window();
    cubicFloatingText.startFloating(guess_word);
}
```

It then floats at the corner of the screen which is not where my view is.

**Comment by UFreedom** [comment]
@laylizzlle ,Thank you for your issue, this is a bug, I'll find out why and then fix this bug, if you find a good solution, please submit `Pull requests` to me, I would be very grateful, thank you!

**Comment by Xopoko** [comment]
floatingText.startFloating(normalView) noramalView should be only View class. Not ImageButton or other View class. Only View.

**Comment by UFreedom** [comment]
@laylizzlle ,We have fix this bug. please update the library to 0.2.0:

```
compile 'com.ufreedom.uikit:FloatingTextLibrary:0.2.0'
```

Any issue is welcome if you have question，Thanks!
