### ISSUE TITLE
显示错位

### ISSUE THREAD

**Issue by andyxialm** [UFreedom/FloatingText#3]
在adapter中设置点击某button显示此控件时，会有较大概率出现错位的问题。貌似频繁操作会触发这个bug

**Comment by UFreedom** [comment]
hello，非常感谢你的issue。
有个哥们已经提了这个bug:#2 ，我正在找解决方案，如果你有好的建议，可以提`Pull requests`给我。非常感谢，我会尽快修复这个bug。

**Comment by UFreedom** [comment]
@ravidsrk  这个bug已经解决了，请更新至最新版本:

```
compile 'com.ufreedom.uikit:FloatingTextLibrary:0.2.0'
```

如有问题，欢迎提issue.Thanks

**Comment by UFreedom** [comment]
#4
